name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ['deploy']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

      - name: Build
        run: npm run build
        working-directory: ./INflow

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./INflow/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
